### PR TITLE
Change to AGPL

### PR DESCRIPTION
**Pull request by iHiD**
We're relicencing these repos to AGPL. See https://github.com/exercism/exercism/issues/5334 for details.

@zeckdude @depsir @crashb Could you all confirm you're happy with this please?

### CODE REVIEW

**Comment by crashb** [comment]
Yes that's fine with me, thanks for checking. Sorry I haven't been able to contribute more beyond a very small bugfix, and I appreciate your thoroughness in mentioning every past contributor here :)

**Comment by depsir** [comment]
I'm ok with that

Il gio 16 lug 2020, 19:40 Jeremy Walker <notifications@github.com> ha
scritto:

**Comment by SleeplessByte** [comment]
I'm going to apply this. If Zeckdude decides to disagree after the fact, I'll go back in and remove their contributions and replace them with my own.

**Comment by zeckdude** [comment]
Sounds good to me!

**Pull request merged**
